onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/rst
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/clear
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/enable
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/count
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/count_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_0/clock_pulses
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/rst
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/clear
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/enable
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/count
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/count_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/counter_1/clock_pulses
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/rst
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/clear
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/count
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/count_cmp
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/count_equal
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_0/count_equal_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/rst
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/clear
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/count
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/count_cmp
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/count_equal
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/comparator_1/count_equal_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/address
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/readdata
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/write_n
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/writedata
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/rst
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/avalon_int
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0INT_set
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INT_set
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CNT_in
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CNT_in
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/AVINTDIS
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTOVR
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTSTS
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0INTSTS
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTEN
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0INTEN
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CNTEN
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CNTEN
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1RST
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0RST
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CNT
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CNT
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CMP
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CMP
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/GP0
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/GP1
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/AVINTDIS_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTOVR_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTSTS_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0INTSTS_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1INTEN_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0INTEN_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CNTEN_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CNTEN_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1RST_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0RST_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CNT_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CNT_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T0CMP_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/T1CMP_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/GP0_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/regfile_0/GP1_sig
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/clk
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_address
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_byteenable
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_irq
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_read
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_readdata
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_waitrequest
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_write
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/d_writedata
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/i_address
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/i_read
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/i_readdata
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/i_readdatavalid
add wave -noupdate /first_nios2_system_tb/first_nios2_system_inst/cpu/i_waitrequest
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
