onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_de2_top/clk
add wave -noupdate /tb_de2_top/resetn
add wave -noupdate /tb_de2_top/keys_s
add wave -noupdate /tb_de2_top/DE2_TOP_1/CLOCK_27
add wave -noupdate /tb_de2_top/DE2_TOP_1/CLOCK_50
add wave -noupdate /tb_de2_top/DE2_TOP_1/EXT_CLOCK
add wave -noupdate /tb_de2_top/DE2_TOP_1/KEY
add wave -noupdate /tb_de2_top/DE2_TOP_1/SW
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX0
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX1
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX2
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX3
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX4
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX5
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX6
add wave -noupdate /tb_de2_top/DE2_TOP_1/HEX7
add wave -noupdate /tb_de2_top/DE2_TOP_1/LEDG
add wave -noupdate /tb_de2_top/DE2_TOP_1/LEDR
add wave -noupdate /tb_de2_top/DE2_TOP_1/UART_TXD
add wave -noupdate /tb_de2_top/DE2_TOP_1/UART_RXD
add wave -noupdate /tb_de2_top/DE2_TOP_1/IRDA_TXD
add wave -noupdate /tb_de2_top/DE2_TOP_1/IRDA_RXD
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_DQ
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_ADDR
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_LDQM
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_UDQM
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_WE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_CAS_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_RAS_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_CS_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_BA_0
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_BA_1
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_CLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/DRAM_CKE
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_DQ
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_ADDR
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_WE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_RST_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_OE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/FL_CE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_DQ
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_ADDR
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_UB_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_LB_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_WE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_CE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/SRAM_OE_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_DATA
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_ADDR
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_CS_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_RD_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_WR_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_RST_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_FSPEED
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_LSPEED
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_INT0
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_INT1
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_DREQ0
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_DREQ1
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_DACK0_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/OTG_DACK1_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_ON
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_BLON
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_RW
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_EN
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_RS
add wave -noupdate /tb_de2_top/DE2_TOP_1/LCD_DATA
add wave -noupdate /tb_de2_top/DE2_TOP_1/SD_DAT
add wave -noupdate /tb_de2_top/DE2_TOP_1/SD_DAT3
add wave -noupdate /tb_de2_top/DE2_TOP_1/SD_CMD
add wave -noupdate /tb_de2_top/DE2_TOP_1/SD_CLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/TDI
add wave -noupdate /tb_de2_top/DE2_TOP_1/TCK
add wave -noupdate /tb_de2_top/DE2_TOP_1/TCS
add wave -noupdate /tb_de2_top/DE2_TOP_1/TDO
add wave -noupdate /tb_de2_top/DE2_TOP_1/I2C_SDAT
add wave -noupdate /tb_de2_top/DE2_TOP_1/I2C_SCLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/PS2_DAT
add wave -noupdate /tb_de2_top/DE2_TOP_1/PS2_CLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_CLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_HS
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_VS
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_BLANK
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_SYNC
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_R
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_G
add wave -noupdate /tb_de2_top/DE2_TOP_1/VGA_B
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_DATA
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_CMD
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_CS_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_WR_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_RD_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_RST_N
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_INT
add wave -noupdate /tb_de2_top/DE2_TOP_1/ENET_CLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_ADCLRCK
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_ADCDAT
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_DACLRCK
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_DACDAT
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_BCLK
add wave -noupdate /tb_de2_top/DE2_TOP_1/AUD_XCK
add wave -noupdate /tb_de2_top/DE2_TOP_1/TD_DATA
add wave -noupdate /tb_de2_top/DE2_TOP_1/TD_HS
add wave -noupdate /tb_de2_top/DE2_TOP_1/TD_VS
add wave -noupdate /tb_de2_top/DE2_TOP_1/TD_RESET
add wave -noupdate /tb_de2_top/DE2_TOP_1/GPIO_0
add wave -noupdate /tb_de2_top/DE2_TOP_1/GPIO_1
add wave -noupdate /tb_de2_top/DE2_TOP_1/counter_r
add wave -noupdate /tb_de2_top/DE2_TOP_1/slowcounter_r
add wave -noupdate -radix unsigned /tb_de2_top/DE2_TOP_1/ramaddr_s
add wave -noupdate -radix unsigned /tb_de2_top/DE2_TOP_1/ramdatain_s
add wave -noupdate -radix unsigned /tb_de2_top/DE2_TOP_1/ramdataout_s
add wave -noupdate /tb_de2_top/DE2_TOP_1/ramwren_s
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/address
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/clock
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/data
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/wren
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/q
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/sub_wire0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/wren_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/wren_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/rden_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/rden_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/data_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/data_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/address_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/address_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clock0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clock1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clocken0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clocken1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clocken2
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/clocken3
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/aclr0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/aclr1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/addressstall_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/addressstall_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/byteena_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/byteena_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/q_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/q_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/eccstatus
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp2_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp_wren_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp2_wren_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp_wren_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_tmp2_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_output_latch
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_ecc_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_q_ecc_tmp_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_current_written_data_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_original_data_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_original_data_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_a_x
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_b_x
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_a_out
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_b_out
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_a_out_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_mask_reg_b_out_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_address_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_address_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_wren_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_wren_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_rden_reg_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_rden_reg_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_read_flag_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_read_flag_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_reread_flag_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_reread_flag_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_reread_flag2_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_reread_flag2_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_write_flag_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_write_flag_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_nmram_write_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_nmram_write_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_indata_aclr_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_address_aclr_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_wrcontrol_aclr_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_indata_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_address_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_wrcontrol_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outdata_aclr_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outdata_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_rdcontrol_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_aclr_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_byteena_aclr_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/good_to_go_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/good_to_go_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_b0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_b1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_inclocken0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_input_clocken_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outdata_clken_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outdata_clken_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outlatch_clken_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_outlatch_clken_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_a_reg
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_core_clocken_b_reg
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/default_val
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_zero_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_zero_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_ones_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_data_ones_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/same_clock_pulse0
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/same_clock_pulse1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_a1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_b1
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_signal_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_force_reread_signal_b
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_good_to_write_a
add wave -noupdate /tb_de2_top/DE2_TOP_1/xtestramblock/altsyncram_component/i_good_to_write_b
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2597851 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 274
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2486991 ps} {2618111 ps}
